spring.application.name=demo-docker
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g8fd1371297d3dc_bdduoc_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)(my_wallet_directory=/app/wallet)))
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ADMIN}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pass1163Meth}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.minimum-idle=${HIKARI_MIN_IDLE:1}
spring.datasource.hikari.maximum-pool-size=${HIKARI_MAX_POOL:5}
spring.datasource.hikari.connection-timeout=${HIKARI_TIMEOUT:120000}
spring.datasource.hikari.initialization-fail-timeout=-1
oracle.net.tns_admin=/app/wallet
oracle.net.wallet_location=/app/wallet
logging.level.org.hibernate.SQL=${LOG_LEVEL_SQL:INFO}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOG_LEVEL_BINDER:INFO}
logging.level.com.example.demo=${LOG_LEVEL_APP:INFO}
serverless.function.url=${SERVERLESS_FUNCTION_URL:http://host.docker.internal:8081}
server.port=${SERVER_PORT:8080}
server.error.include-message=always
server.error.include-binding-errors=always
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always